version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
     - node_modules:/usr/src/app/node_modules
    command: sh -c "yarn start"
    ports:
     - "3000:3000"
    environment:
     - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules: